# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/magic/.local/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/magic/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/magic/labs/arch/hl_mai_lab_02-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/magic/labs/arch/hl_mai_lab_02-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/magic/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/magic/.local/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/magic/labs/arch/hl_mai_lab_02-main/CMakeFiles /home/magic/labs/arch/hl_mai_lab_02-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/magic/labs/arch/hl_mai_lab_02-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named user_service

# Build rule for target.
user_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 user_service
.PHONY : user_service

# fast build rule for target.
user_service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/build
.PHONY : user_service/fast

#=============================================================================
# Target rules for targets named conference_service

# Build rule for target.
conference_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 conference_service
.PHONY : conference_service

# fast build rule for target.
conference_service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/build
.PHONY : conference_service/fast

#=============================================================================
# Target rules for targets named lecture_service

# Build rule for target.
lecture_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lecture_service
.PHONY : lecture_service

# fast build rule for target.
lecture_service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/build
.PHONY : lecture_service/fast

config/config.o: config/config.cpp.o
.PHONY : config/config.o

# target to build an object file
config/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/config/config.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/config/config.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/config/config.cpp.o
.PHONY : config/config.cpp.o

config/config.i: config/config.cpp.i
.PHONY : config/config.i

# target to preprocess a source file
config/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/config/config.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/config/config.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/config/config.cpp.i
.PHONY : config/config.cpp.i

config/config.s: config/config.cpp.s
.PHONY : config/config.s

# target to generate assembly for a file
config/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/config/config.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/config/config.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/config/config.cpp.s
.PHONY : config/config.cpp.s

database/conference.o: database/conference.cpp.o
.PHONY : database/conference.o

# target to build an object file
database/conference.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/conference.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/conference.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/conference.cpp.o
.PHONY : database/conference.cpp.o

database/conference.i: database/conference.cpp.i
.PHONY : database/conference.i

# target to preprocess a source file
database/conference.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/conference.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/conference.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/conference.cpp.i
.PHONY : database/conference.cpp.i

database/conference.s: database/conference.cpp.s
.PHONY : database/conference.s

# target to generate assembly for a file
database/conference.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/conference.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/conference.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/conference.cpp.s
.PHONY : database/conference.cpp.s

database/database.o: database/database.cpp.o
.PHONY : database/database.o

# target to build an object file
database/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/database.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/database.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/database.cpp.o
.PHONY : database/database.cpp.o

database/database.i: database/database.cpp.i
.PHONY : database/database.i

# target to preprocess a source file
database/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/database.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/database.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/database.cpp.i
.PHONY : database/database.cpp.i

database/database.s: database/database.cpp.s
.PHONY : database/database.s

# target to generate assembly for a file
database/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/database.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/database.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/database.cpp.s
.PHONY : database/database.cpp.s

database/lecture.o: database/lecture.cpp.o
.PHONY : database/lecture.o

# target to build an object file
database/lecture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/lecture.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/lecture.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/lecture.cpp.o
.PHONY : database/lecture.cpp.o

database/lecture.i: database/lecture.cpp.i
.PHONY : database/lecture.i

# target to preprocess a source file
database/lecture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/lecture.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/lecture.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/lecture.cpp.i
.PHONY : database/lecture.cpp.i

database/lecture.s: database/lecture.cpp.s
.PHONY : database/lecture.s

# target to generate assembly for a file
database/lecture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/lecture.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/lecture.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/lecture.cpp.s
.PHONY : database/lecture.cpp.s

database/user.o: database/user.cpp.o
.PHONY : database/user.o

# target to build an object file
database/user.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/user.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/user.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/user.cpp.o
.PHONY : database/user.cpp.o

database/user.i: database/user.cpp.i
.PHONY : database/user.i

# target to preprocess a source file
database/user.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/user.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/user.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/user.cpp.i
.PHONY : database/user.cpp.i

database/user.s: database/user.cpp.s
.PHONY : database/user.s

# target to generate assembly for a file
database/user.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/database/user.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/database/user.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/database/user.cpp.s
.PHONY : database/user.cpp.s

services/conference/main.o: services/conference/main.cpp.o
.PHONY : services/conference/main.o

# target to build an object file
services/conference/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/services/conference/main.cpp.o
.PHONY : services/conference/main.cpp.o

services/conference/main.i: services/conference/main.cpp.i
.PHONY : services/conference/main.i

# target to preprocess a source file
services/conference/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/services/conference/main.cpp.i
.PHONY : services/conference/main.cpp.i

services/conference/main.s: services/conference/main.cpp.s
.PHONY : services/conference/main.s

# target to generate assembly for a file
services/conference/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conference_service.dir/build.make CMakeFiles/conference_service.dir/services/conference/main.cpp.s
.PHONY : services/conference/main.cpp.s

services/lecture/main.o: services/lecture/main.cpp.o
.PHONY : services/lecture/main.o

# target to build an object file
services/lecture/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/services/lecture/main.cpp.o
.PHONY : services/lecture/main.cpp.o

services/lecture/main.i: services/lecture/main.cpp.i
.PHONY : services/lecture/main.i

# target to preprocess a source file
services/lecture/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/services/lecture/main.cpp.i
.PHONY : services/lecture/main.cpp.i

services/lecture/main.s: services/lecture/main.cpp.s
.PHONY : services/lecture/main.s

# target to generate assembly for a file
services/lecture/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lecture_service.dir/build.make CMakeFiles/lecture_service.dir/services/lecture/main.cpp.s
.PHONY : services/lecture/main.cpp.s

services/user/main.o: services/user/main.cpp.o
.PHONY : services/user/main.o

# target to build an object file
services/user/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/services/user/main.cpp.o
.PHONY : services/user/main.cpp.o

services/user/main.i: services/user/main.cpp.i
.PHONY : services/user/main.i

# target to preprocess a source file
services/user/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/services/user/main.cpp.i
.PHONY : services/user/main.cpp.i

services/user/main.s: services/user/main.cpp.s
.PHONY : services/user/main.s

# target to generate assembly for a file
services/user/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_service.dir/build.make CMakeFiles/user_service.dir/services/user/main.cpp.s
.PHONY : services/user/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... conference_service"
	@echo "... lecture_service"
	@echo "... user_service"
	@echo "... config/config.o"
	@echo "... config/config.i"
	@echo "... config/config.s"
	@echo "... database/conference.o"
	@echo "... database/conference.i"
	@echo "... database/conference.s"
	@echo "... database/database.o"
	@echo "... database/database.i"
	@echo "... database/database.s"
	@echo "... database/lecture.o"
	@echo "... database/lecture.i"
	@echo "... database/lecture.s"
	@echo "... database/user.o"
	@echo "... database/user.i"
	@echo "... database/user.s"
	@echo "... services/conference/main.o"
	@echo "... services/conference/main.i"
	@echo "... services/conference/main.s"
	@echo "... services/lecture/main.o"
	@echo "... services/lecture/main.i"
	@echo "... services/lecture/main.s"
	@echo "... services/user/main.o"
	@echo "... services/user/main.i"
	@echo "... services/user/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

